# Generated by Django 6.0.3 on 2026-03-28 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CriticalPathPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtask_name', models.CharField(max_length=200)),
                ('predicted_score', models.FloatField()),
                ('ground_truth_score', models.FloatField()),
                ('in_degree', models.FloatField()),
                ('out_degree', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='OptimalAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.IntegerField()),
                ('subtask_id', models.IntegerField()),
                ('cost', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='NormalizedEdge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.IntegerField()),
                ('subtask_id', models.IntegerField()),
                ('avg_duration', models.FloatField(default=0)),
                ('avg_defects', models.FloatField(default=0)),
                ('total_tasks_done', models.FloatField(default=0)),
                ('total_defects', models.FloatField(default=0)),
            ],
            options={
                'unique_together': {('employee_id', 'subtask_id')},
            },
        ),
    ]
