# Generated by Django 6.0.3 on 2026-04-10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubtaskRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('br_id', models.IntegerField()),
                ('subtask_a', models.CharField(max_length=255)),
                ('subtask_b', models.CharField(max_length=255)),
                ('pair_text', models.TextField(blank=True)),
                ('relationship_label', models.CharField(choices=[('FS', 'Finish-Start'), ('SF', 'Start-Finish'), ('FF', 'Finish-Finish'), ('SS', 'Start-Start'), ('NO_RELATION', 'No Relation')], max_length=20)),
                ('predicted_relationship', models.CharField(blank=True, choices=[('FS', 'Finish-Start'), ('SF', 'Start-Finish'), ('FF', 'Finish-Finish'), ('SS', 'Start-Start'), ('NO_RELATION', 'No Relation')], max_length=20)),
                ('confidence', models.FloatField(default=0.0)),
            ],
            options={
                'unique_together': {('br_id', 'subtask_a', 'subtask_b')},
            },
        ),
    ]
