# Generated by Django 5.2.13 on 2026-04-11 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling_app', '0002_subtaskrelationship'),
    ]

    operations = [
        migrations.CreateModel(
            name='RuntimeSubtaskPair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('br_id', models.IntegerField()),
                ('subtask_a', models.CharField(max_length=200)),
                ('subtask_b', models.CharField(max_length=200)),
            ],
            options={
                'unique_together': {('br_id', 'subtask_a', 'subtask_b')},
            },
        ),
    ]
