# Generated by Django 5.2.13 on 2026-04-14 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling_app', '0003_runtimesubtaskpair'),
    ]

    operations = [
        migrations.AddField(
            model_name='criticalpathprediction',
            name='br_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='optimalassignment',
            name='br_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='optimalassignment',
            name='subtask_name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
