# Generated by Django 5.2.13 on 2026-04-20 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling_app', '0004_criticalpathprediction_br_id_optimalassignment_br_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='criticalpathprediction',
            name='ground_truth_score',
        ),
    ]
