# Generated by Django 5.2.13 on 2026-04-20 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling_app', '0005_remove_criticalpathprediction_ground_truth_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='optimalassignment',
            name='employee_name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
