# Generated by Django 6.0.2 on 2026-03-19 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('business_requirements', models.TextField()),
                ('project_type', models.CharField(default='General', max_length=100)),
            ],
        ),
    ]
