# Generated by Django 6.0.3 on 2026-03-28 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0002_projecttype_alter_project_project_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('br_id', models.IntegerField(unique=True)),
                ('text', models.TextField()),
                ('tokens', models.TextField(blank=True, default='')),
                ('primary_task_type', models.CharField(max_length=200)),
                ('primary_task_subtype', models.CharField(max_length=200)),
                ('num_system_requirements', models.IntegerField(default=0)),
                ('uncertainty', models.FloatField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='projecttype',
            name='innovation',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='projecttype',
            name='risk',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='projecttype',
            name='roi_horizon',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.CreateModel(
            name='SystemRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_req_id', models.CharField(max_length=50)),
                ('task_type', models.CharField(max_length=200)),
                ('task_subtype', models.CharField(max_length=200)),
                ('required_experience_level', models.CharField(max_length=100)),
                ('uncertainty', models.FloatField(default=0)),
                ('business_requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='system_requirements', to='project_app.businessrequirement')),
            ],
        ),
    ]
