# Generated by Django 5.2.13 on 2026-04-11 18:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0003_businessrequirement_projecttype_innovation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessrequirement',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='br_items', to='project_app.project'),
        ),
    ]
