# Generated by Django 6.0.3 on 2026-03-28 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='employee_id',
            field=models.IntegerField(default=0, unique=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='first_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='employee',
            name='last_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='experiencelevel',
            name='autonomy',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='experiencelevel',
            name='decision_scope',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='experiencelevel',
            name='leadership',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='experiencelevel',
            name='max_years',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='experiencelevel',
            name='min_years',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='experiencelevel',
            name='primary_focus',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='experiencelevel',
            name='rank',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='experiencelevel',
            name='system_impact',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='experiencelevel',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='EmployeeVector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vector_data', models.JSONField()),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vector', to='employee_app.employee')),
            ],
        ),
    ]
