# Generated by Django 6.0.2 on 2026-03-21 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_type',
            field=models.CharField(default='General', max_length=255),
        ),
    ]
