# Generated by Django 6.0.3 on 2026-03-28 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_app', '0002_employee_employee_id_employee_first_name_and_more'),
        ('task_app', '0002_alter_task_task_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubtaskVector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtask_id', models.IntegerField(unique=True)),
                ('task_name', models.CharField(max_length=200)),
                ('subtask_name', models.CharField(max_length=200)),
                ('task_norm', models.CharField(blank=True, default='', max_length=200)),
                ('sub_norm', models.CharField(blank=True, default='', max_length=200)),
                ('vector_data', models.JSONField()),
            ],
        ),
        migrations.AddField(
            model_name='employeetask',
            name='experience_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee_app.experiencelevel'),
        ),
        migrations.AddField(
            model_name='employeetask',
            name='total_defects',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='employeetask',
            name='total_hours',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='employeetask',
            name='total_tasks_done',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='task',
            name='subtask_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='task',
            name='task_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='employeetask',
            name='defects',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='employeetask',
            name='working_hours',
            field=models.FloatField(default=0),
        ),
    ]
